skip_lfs: true

pre-commit:
  commands:
    check:
      run: task -s lint

pre-push:
  commands:
    test:
      run: task -s test

commit-msg:
  commands:
    message:
      run: task -s commit-msg -- {1}

