skip_lfs: true
glob_matcher: doublestar

pre-commit:
  parallel: true
  commands:
    lint:
      run: | 
        set -euo pipefail;
        lefthook run lint;

pre-push:
  parallel: true
  commands:
    tests:
      run: | 
        set -euo pipefail;
        lefthook run test;

commit-msg:
  parallel: true
  commands:
    length:
      run: |
        MSG_FILE="{1}"
        TITLE=$(head -n1 "$MSG_FILE")

        if [ ${#TITLE} -gt 100 ]; then
          echo "Commit title too long (${#TITLE}/100)"
          exit 1
        fi
    conventional:
      run: |
        MSG_FILE="{1}"
        TITLE=$(head -n1 "$MSG_FILE")

        if ! echo "$TITLE" | grep -Eq '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)(\([a-zA-Z0-9_-]+\))?(!)?: .+$'; then
          echo "Commit message does not follow Conventional Commits"
          exit 1
        fi

lint:
  parallel: true
  commands:
    cpp:
      run: |
        set -euo pipefail
        [ -z "{staged_files}" ] && exit 0
        clang-format --dry-run --Werror {staged_files}
        # cppcheck --enable=all --inconclusive --error-exitcode=1 --check-config {staged_files}
      glob:
        - "**/*.{cpp,c,hpp,h}"
    typo:
      run: |
        set -euo pipefail
        if ! command -v typos >/dev/null 2>&1; then
          echo "Please install typos CLI"
          exit 1
        fi
        typos {staged_files}
    header_once:
      run: |
        result=0
        for file in "{staged_files}"; do
          [[ -f "$file" ]] || continue
          first_line=$(head -n 1 "$file")
          last_line=$(grep -v '^[[:space:]]*$' "$file" | tail -n 1)
          if [[ ! "$first_line" =~ ^#ifndef ]]; then
            echo "$file: does not start with #ifndef"
            result=1
          fi
          if [[ ! "$last_line" =~ ^#endif[[:space:]]*$ ]]; then
            echo "$file: does not end with #endif"
            result=1
          fi
        done

        exit $result 
      glob:
        - "**/*.{h,hpp}"


lint-force:
  parallel: true
  commands:
    cpp:
      run: |
        set -euo pipefail
        [ -z "{staged_files}" ] && exit 0
        clang-format --Werror {staged_files}
        # cppcheck --enable=all --error-exitcode=1 --check-config {staged_files}
      glob:
        - "**/*.{cpp,c,hpp,h}"
    typo:
      run: |
        set -euo pipefail
        if ! command -v typos >/dev/null 2>&1; then
          echo "Please install typos CLI"
          exit 1
        fi
        typos -w {staged_files}
    header_once:
      run: |
        result=0
        for file in "{staged_files}"; do
          [[ -f "$file" ]] || continue
          first_line=$(head -n 1 "$file")
          last_line=$(grep -v '^[[:space:]]*$' "$file" | tail -n 1)
          if [[ ! "$first_line" =~ ^#ifndef ]]; then
            echo "$file: does not start with #ifndef"
            result=1
          fi
          if [[ ! "$last_line" =~ ^#endif[[:space:]]*$ ]]; then
            echo "$file: does not end with #endif"
            result=1
          fi
        done

        exit $result 
      glob:
        - "**/*.{h,hpp}"

lint-all:
  parallel: true
  commands:
    cpp:
      run: |
        set -euo pipefail
        [ -z "{all_files}" ] && exit 0
        clang-format --dry-run --Werror {all_files}
        # cppcheck --enable=all --error-exitcode=1 --check-config {all_files}
      glob:
        - "**/*.{cpp,c,hpp,h}"
    typos:
      run: |
        set -euo pipefail
        if ! command -v typos >/dev/null 2>&1; then
          echo "Please install typos CLI"
          exit 1
        fi
        typos
    header_once:
      run: |
        result=0
        for file in "{all_files}"; do
          [[ -f "$file" ]] || continue
          first_line=$(head -n 1 "$file")
          last_line=$(grep -v '^[[:space:]]*$' "$file" | tail -n 1)
          if [[ ! "$first_line" =~ ^#ifndef ]]; then
            echo "$file: does not start with #ifndef"
            result=1
          fi
          if [[ ! "$last_line" =~ ^#endif[[:space:]]*$ ]]; then
            echo "$file: does not end with #endif"
            result=1
          fi
        done

        exit $result 
      glob:
        - "**/*.{h,hpp}"

lint-force-all:
  parallel: true
  commands:
    cpp:
      run: |
        set -euo pipefail
        [ -z "{all_files}" ] && exit 0
        clang-format --Werror {all_files}
        # cppcheck --enable=all --error-exitcode=1 --check-config {all_files}
      glob:
        - "**/*.{cpp,c,hpp,h}"
    typos:
      run: |
        set -euo pipefail
        if ! command -v typos >/dev/null 2>&1; then
          echo "Please install typos CLI"
          exit 1
        fi
        typos -w
    header_once:
      run: |
        result=0
        echo "?{all_files}"
        for file in "{all_files}"; do
          [[ -f "$file" ]] || continue
          first_line=$(head -n 1 "$file")
          last_line=$(grep -v '^[[:space:]]*$' "$file" | tail -n 1)
          if [[ ! "$first_line" =~ ^#ifndef ]]; then
            echo "$file: does not start with #ifndef"
            result=1
          fi
          if [[ ! "$last_line" =~ ^#endif[[:space:]]*$ ]]; then
            echo "$file: does not end with #endif"
            result=1
          fi
        done

        exit $result 
      glob:
        - "**/*.{h,hpp}"

install:
  parallel: true
  commands:
    lefthook:
      run: |
        set -euo pipefail
        lefthook install
    build:
      run: |
        set -euo pipefail
        lefthook run build

run: 
  commands:
    cli:
      run: |
        set -euo pipefail
        ./build/mapgen

build:
  commands:
    run-build:
      run: |
        set -euo pipefail
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${DEBUG:-OFF} \
          -DBUILD_CLI=${CLI:-OFF} \
          -DBUILD_TESTING=${TEST:-ON}

        cmake --build build --parallel
        ln -sf build/compile_commands.json compile_commands.json

build-clean:
  commands:
    run-build:
      run: |
        set -euo pipefail
        rm -fr build
        cmake -S . -B build \
          -DCMAKE_BUILD_TYPE=${DEBUG:-OFF} \
          -DBUILD_CLI=${CLI:-OFF} \
          -DBUILD_TESTING=${TEST:-ON}
        cmake --build build --parallel
        ln -sf build/compile_commands.json compile_commands.json

test:
  commands:
    run-tests:
      run: |
        set -euo pipefail
        DEBUG=ON TEST=ON lefthook run build
        ctest --test-dir build --rerun-failed --output-on-failure # --verbose

test-clean:
  commands:
    run-tests:
      run: |
        set -euo pipefail
        DEBUG=ON TEST=ON lefthook run build-clean
        ctest --test-dir build --rerun-failed --output-on-failure # --verbose

